const EVENTS = {
  "employee.password_reset.otp_requested": {
    description: "Employee portal password recovery; send a verification code",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "employee_user",
    skipContactAutomation: true,
    requiredPayloadFields: ["otpCode", "expiryMinutes", "venueName"],
    samplePayload: {
      employeeName: "Alex Rivera",
      employeeFirstName: "Alex",
      otpCode: "123456",
      expiryMinutes: 10,
      venueName: "Movira Main Branch",
    },
  },
  "booking.confirmed": {
    description: "Customer booking confirmed; send confirmation with details",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "booking",
    requiredPayloadFields: ["guestName", "bookingNumber", "venueName"],
    samplePayload: {
      guestName: "Yogesh",
      bookingNumber: "BK-2026-001",
      venueName: "Mumbai Sports Park",
      bookingDate: "2026-05-15",
      totalAmount: "$120.00",
      paymentLink: "",
    },
  },
  "payment.received": {
    description: "Payment captured for a booking; send receipt",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "payment",
    requiredPayloadFields: ["guestName", "bookingNumber", "venueName", "amountPaid"],
    samplePayload: {
      guestName: "Yogesh",
      bookingNumber: "BK-2026-001",
      venueName: "Mumbai Sports Park",
      amountPaid: "$120.00",
      gateway: "Stripe",
    },
  },
  "payment.link.requested": {
    description: "Send a payment link to the customer to complete checkout",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "payment",
    requiredPayloadFields: ["guestName", "bookingNumber", "venueName", "paymentLink", "amountDue"],
    samplePayload: {
      guestName: "Yogesh",
      bookingNumber: "BK-2026-001",
      venueName: "Mumbai Sports Park",
      paymentLink: "https://example.com/pay/xxx",
      amountDue: "$120.00",
    },
  },
  "waiver.link.requested": {
    description: "Send a waiver signature link to a guest",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "waiver",
    requiredPayloadFields: ["guestName", "venueName", "waiverLink"],
    samplePayload: {
      guestName: "Yogesh",
      venueName: "Mumbai Sports Park",
      waiverLink: "https://example.com/waiver/xxx",
    },
  },
  "waiver.completed": {
    description: "Guest has signed a waiver; send confirmation with expiry info",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "waiver",
    requiredPayloadFields: ["guestName", "venueName"],
    samplePayload: {
      guestName: "Yogesh",
      venueName: "Mumbai Sports Park",
      expiryDate: "2026-12-31",
      expiryDays: 365,
    },
  },
  "waiver.expiring": {
    description: "Waiver expiring soon; reminder to guest",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "waiver",
    requiredPayloadFields: ["guestName", "venueName", "expiryDate"],
    samplePayload: {
      guestName: "Yogesh",
      venueName: "Mumbai Sports Park",
      expiryDate: "2026-06-15",
    },
  },
  "customer_experience.visit.completed": {
    description: "Guest visit completed and is available for Customer Experience follow-up",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "customer_experience_visit",
    requiredPayloadFields: ["guestName", "venueName", "visitDate"],
    samplePayload: {
      guestName: "Avery Guest",
      venueName: "Movira St. Catharines",
      bookingNumber: "BK-2026-001",
      activityName: "1 Hour Jump Pass",
      visitDate: "2026-07-01",
      experienceVisitId: 456,
    },
  },
  "customer_experience.feedback.requested": {
    description: "Request feedback from a guest after an eligible completed visit",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "customer_experience_visit",
    requiredPayloadFields: ["guestName", "venueName", "feedbackUrl"],
    samplePayload: {
      guestName: "Avery Guest",
      venueName: "Movira St. Catharines",
      bookingNumber: "BK-2026-001",
      activityName: "1 Hour Jump Pass",
      visitDate: "2026-07-01",
      feedbackUrl: "https://example.com/feedback/abc",
      experienceVisitId: 456,
    },
  },
  "customer_experience.feedback.received": {
    description: "Guest feedback was received for a completed visit",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "customer_experience_feedback",
    requiredPayloadFields: ["guestName", "venueName", "ratingOverall"],
    samplePayload: {
      guestName: "Avery Guest",
      venueName: "Movira St. Catharines",
      bookingNumber: "BK-2026-001",
      ratingOverall: 4,
      sentiment: "positive",
      experienceScore: 80,
      experienceFeedbackId: 123,
      experienceVisitId: 456,
    },
  },
  "customer_experience.feedback.at_risk": {
    description: "Low score, safety issue, or contact request needs Customer Experience recovery attention",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "customer_experience_feedback",
    requiredPayloadFields: ["guestName", "venueName", "ratingOverall"],
    samplePayload: {
      guestName: "Avery Guest",
      venueName: "Movira St. Catharines",
      bookingNumber: "BK-2026-001",
      ratingOverall: 1,
      sentiment: "at_risk",
      experienceScore: 0,
      issueTags: ["safety", "wait_time"],
      contactRequested: true,
      experienceFeedbackId: 123,
      experienceVisitId: 456,
    },
  },
  "customer_experience.recovery.created": {
    description: "Recovery task created for feedback that needs follow-up",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "customer_experience_recovery",
    requiredPayloadFields: ["guestName", "venueName", "priority"],
    samplePayload: {
      guestName: "Avery Guest",
      venueName: "Movira St. Catharines",
      priority: "urgent",
      dueAt: "2026-07-02T12:00:00.000Z",
      experienceRecoveryTaskId: 88,
      experienceFeedbackId: 123,
      experienceVisitId: 456,
    },
  },
  "customer_experience.recovery.reply_requested": {
    description: "Staff requested a Customer Experience recovery reply to be sent through CRM",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "customer_experience_recovery",
    requiredPayloadFields: ["guestName", "venueName", "replyMessage"],
    samplePayload: {
      guestName: "Avery Guest",
      venueName: "Movira St. Catharines",
      replyMessage: "Thank you for the feedback. A manager will follow up shortly.",
      recoveryStatus: "contacted",
      experienceRecoveryTaskId: 88,
      experienceFeedbackId: 123,
      experienceVisitId: 456,
    },
  },
  "customer_experience.recovery.resolved": {
    description: "Recovery task was resolved after guest follow-up",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "customer_experience_recovery",
    requiredPayloadFields: ["guestName", "venueName"],
    samplePayload: {
      guestName: "Avery Guest",
      venueName: "Movira St. Catharines",
      resolutionNote: "Manager completed guest recovery.",
      experienceRecoveryTaskId: 88,
      experienceFeedbackId: 123,
      experienceVisitId: 456,
    },
  },
  "customer_experience.reward.issued": {
    description: "Staff verified a guest's public review claim and issued a thank-you reward code",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "customer_experience_reward_claim",
    requiredPayloadFields: ["guestName", "venueName", "rewardCode"],
    samplePayload: {
      guestName: "Avery Guest",
      venueName: "Movira St. Catharines",
      rewardCode: "RW-7K2M4P",
      rewardMessage: "Show this code at the front desk for 10% off your next visit.",
      reviewSite: "google",
      experienceRewardClaimId: 12,
      experienceVisitId: 456,
    },
  },
  "saas.onboarding.started": {
    description: "New SaaS park onboarding has started; send owner welcome and next steps",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "saas_park",
    requiredPayloadFields: ["guestName", "venueName"],
    samplePayload: {
      guestName: "Yogesh Niranjan",
      venueName: "Summit Splash Park",
      onboardingPhase: "Park workspace",
      modules: "bookings, crm",
    },
  },
  "saas.invoice.issued": {
    description: "SaaS invoice created or updated; send invoice summary to customer owner",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "saas_invoice",
    requiredPayloadFields: ["guestName", "venueName", "invoiceNumber", "totalAmount", "dueDate"],
    samplePayload: {
      guestName: "Yogesh Niranjan",
      venueName: "Summit Splash Park",
      invoiceNumber: "SaaS-0001-00001",
      totalAmount: "$548.00",
      dueDate: "Jul 08, 2026",
    },
  },
  "saas.invoice.payment_link": {
    description: "SaaS invoice payment link generated; send payable link to customer owner",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "saas_invoice",
    requiredPayloadFields: ["guestName", "venueName", "invoiceNumber", "paymentLink", "amountDue"],
    samplePayload: {
      guestName: "Yogesh Niranjan",
      venueName: "Summit Splash Park",
      invoiceNumber: "SaaS-0001-00001",
      paymentLink: "https://movira.example/pay/abc",
      amountDue: "$548.00",
    },
  },
  "saas.invoice.paid": {
    description: "SaaS invoice paid; send receipt and account status confirmation",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "saas_invoice",
    requiredPayloadFields: ["guestName", "venueName", "invoiceNumber", "paidAmount"],
    samplePayload: {
      guestName: "Yogesh Niranjan",
      venueName: "Summit Splash Park",
      invoiceNumber: "SaaS-0001-00001",
      paidAmount: "$548.00",
      paidAt: "Jul 01, 2026",
    },
  },
  "saas.invoice.reminder": {
    description: "SaaS invoice due or overdue; send reminder without releasing suppression controls",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "saas_invoice",
    requiredPayloadFields: ["guestName", "venueName", "invoiceNumber", "balanceDue", "dueDate"],
    samplePayload: {
      guestName: "Yogesh Niranjan",
      venueName: "Summit Splash Park",
      invoiceNumber: "SaaS-0001-00001",
      balanceDue: "$548.00",
      dueDate: "Jul 08, 2026",
      reminderStage: "due_soon",
    },
  },
  "saas.invoice.voided": {
    description: "SaaS invoice voided; notify the customer owner that the invoice is no longer payable",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "saas_invoice",
    requiredPayloadFields: ["guestName", "venueName", "invoiceNumber"],
    samplePayload: {
      guestName: "Yogesh Niranjan",
      venueName: "Summit Splash Park",
      invoiceNumber: "SaaS-0001-00001",
      status: "void",
    },
  },
  "saas.invoice.refunded": {
    description: "SaaS invoice payment refunded; send refund confirmation to the customer owner",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "saas_invoice",
    requiredPayloadFields: ["guestName", "venueName", "invoiceNumber", "paidAmount"],
    samplePayload: {
      guestName: "Yogesh Niranjan",
      venueName: "Summit Splash Park",
      invoiceNumber: "SaaS-0001-00001",
      paidAmount: "$0.00",
      status: "refunded",
    },
  },
  "saas.billing.past_due": {
    description: "SaaS billing is past due; notify the customer owner before suspension",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "saas_park",
    requiredPayloadFields: ["guestName", "venueName", "invoiceNumber", "balanceDue"],
    samplePayload: {
      guestName: "Yogesh Niranjan",
      venueName: "Summit Splash Park",
      invoiceNumber: "SaaS-0001-00001",
      balanceDue: "$548.00",
      lifecycleState: "past_due",
    },
  },
  "saas.billing.suspended": {
    description: "SaaS billing hold applied; notify the customer owner that access is paused",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "saas_park",
    requiredPayloadFields: ["guestName", "venueName", "invoiceNumber", "balanceDue"],
    samplePayload: {
      guestName: "Yogesh Niranjan",
      venueName: "Summit Splash Park",
      invoiceNumber: "SaaS-0001-00001",
      balanceDue: "$548.00",
      lifecycleState: "suspended",
    },
  },
  "saas.billing.recovered": {
    description: "SaaS billing recovered; notify the customer owner that the account is back in good standing",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "saas_park",
    requiredPayloadFields: ["guestName", "venueName"],
    samplePayload: {
      guestName: "Yogesh Niranjan",
      venueName: "Summit Splash Park",
      lifecycleState: "recovered",
    },
  },
  "saas.park.go_live": {
    description: "SaaS park approved for live operations; notify the customer owner",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "saas_park",
    requiredPayloadFields: ["guestName", "venueName"],
    samplePayload: {
      guestName: "Yogesh Niranjan",
      venueName: "Summit Splash Park",
      parkStatus: "live",
    },
  },
  "saas.park.go_live_blocked": {
    description: "SaaS park go-live blocked by missing checks; notify the customer owner",
    sourceSystem: "aeroSportsAdmin",
    sourceResourceType: "saas_park",
    requiredPayloadFields: ["guestName", "venueName"],
    samplePayload: {
      guestName: "Yogesh Niranjan",
      venueName: "Summit Splash Park",
      parkStatus: "needs_checks",
    },
  },
};

function isRegistered(eventType) {
  return Object.prototype.hasOwnProperty.call(EVENTS, eventType);
}

function listEvents() {
  return Object.entries(EVENTS).map(([eventType, meta]) => ({ eventType, ...meta }));
}

function getEvent(eventType) {
  return EVENTS[eventType] || null;
}

module.exports = {
  EVENTS,
  isRegistered,
  listEvents,
  getEvent,
};
