const PROVIDER_OPTIONS = [
  {
    provider: "movira_ses",
    label: "Movira SES",
    mode: "default",
    description: "Recommended production default. Built-in Movira email infrastructure backed by Amazon SES.",
    supports: ["transactional", "marketing"],
    capabilities: {
      sending: true,
      openClickTracking: true,
      deliveryWebhook: true,
      bounceWebhook: true,
      complaintWebhook: true,
      notes: "Full analytics through Movira SES configuration sets, SNS, and SQS webhook workers.",
    },
    requiresCustomerCredentials: false,
    fields: [],
  },
  {
    provider: "customer_ses",
    label: "Customer Amazon SES",
    mode: "bring_your_own",
    description: "Use the customer's own Amazon SES account and identity. Best BYO option when SES event destinations are configured.",
    supports: ["transactional", "marketing"],
    capabilities: {
      sending: true,
      openClickTracking: true,
      deliveryWebhook: true,
      bounceWebhook: true,
      complaintWebhook: true,
      notes: "Full analytics are available when the customer's SES configuration set publishes events to Movira.",
    },
    requiresCustomerCredentials: true,
    fields: ["region", "accessKeyId", "secretAccessKey", "fromEmail", "configurationSet"],
  },
  {
    provider: "customer_sendgrid",
    label: "Customer SendGrid",
    mode: "bring_your_own",
    description: "Use the customer's own SendGrid API key. Full analytics require a SendGrid Event Webhook adapter.",
    supports: ["transactional", "marketing"],
    capabilities: {
      sending: true,
      openClickTracking: true,
      deliveryWebhook: true,
      bounceWebhook: true,
      complaintWebhook: true,
      notes: "Provider delivery events require SendGrid Event Webhook integration. Movira open/click tracking still works independently.",
    },
    requiresCustomerCredentials: true,
    fields: ["apiKey", "fromEmail"],
  },
  {
    provider: "customer_mailgun",
    label: "Customer Mailgun",
    mode: "bring_your_own",
    description: "Use the customer's own Mailgun sending domain and API key. Full analytics require Mailgun webhooks.",
    supports: ["transactional", "marketing"],
    capabilities: {
      sending: true,
      openClickTracking: true,
      deliveryWebhook: true,
      bounceWebhook: true,
      complaintWebhook: true,
      notes: "Movira adds Mailgun variables for message matching. Configure Mailgun webhooks to /api/webhooks/mailgun for provider delivery events.",
    },
    requiresCustomerCredentials: true,
    fields: ["apiKey", "domain", "region", "fromEmail"],
  },
  {
    provider: "customer_postmark",
    label: "Customer Postmark",
    mode: "bring_your_own",
    description: "Use the customer's own Postmark server token. Full analytics require Postmark webhooks.",
    supports: ["transactional", "marketing"],
    capabilities: {
      sending: true,
      openClickTracking: true,
      deliveryWebhook: true,
      bounceWebhook: true,
      complaintWebhook: true,
      notes: "Movira adds Postmark metadata for message matching. Configure Postmark webhooks to /api/webhooks/postmark for provider delivery events.",
    },
    requiresCustomerCredentials: true,
    fields: ["serverToken", "fromEmail"],
  },
];

module.exports = { PROVIDER_OPTIONS };
